#!/usr/bin/env python

import sys

from micro_epsilon_scancontrol_driver.gui import ScanControlGui
from micro_epsilon_scancontrol_driver.gui import ScanControlManualSettingsGui
from rqt_gui.main import Main

plugin = 'micro_epsilon_scancontrol_driver'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))